stages:
  - name: Build & Publish
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: discord-bots-abspen1Alt:v1.0
    when:
      branch: {}
      event:
        include:
          - push
          - pull request
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./discord-bot-usaa-dc.yaml
    when:
      branch: {}
      event:
        include:
          - push
          - pull request
branch:
  include:
    - usaa
notification: {}
