apiVersion: apps/v1
kind: Deployment
metadata:
  name: botguy
  namespace: discord-bots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: botguy
  template:
    metadata:
      labels:
        app: botguy
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: botguy
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        imagePullPolicy: Always
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              key: botguy-token
              name: bot-secrets
        - name: PUBLIC
          valueFrom:
            secretKeyRef:
              key: botguy-public
              name: bot-secrets
        - name: BOT_ID
          valueFrom:
            secretKeyRef:
              key: botguy-id
              name: bot-secrets
        - name: SECRET
          valueFrom:
            secretKeyRef:
              key: botguy-secret
              name: bot-secrets
        - name: TENOR_KEY
          valueFrom:
            secretKeyRef:
              key: botguy-tenor-key
              name: bot-secrets
        - name: USER_ID
          valueFrom:
            secretKeyRef:
              key: abspen1-id
              name: bot-secrets
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              key: REDIS_PASS
              name: redis-pass
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              key: REDIS_HOST
              name: redis-pass