apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  namespace: bots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      imagePullSecrets:
        - name: guldentech-harbor-registry
      containers:
        - name: discord-bot
          image: harbor.guldentech.com/austin-spencer/discord-bot:TAG
          imagePullPolicy: Always
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  key: botguy-token
                  name: discord-secrets
            - name: PUBLIC
              valueFrom:
                secretKeyRef:
                  key: botguy-public
                  name: discord-secrets
            - name: BOT_ID
              valueFrom:
                secretKeyRef:
                  key: botguy-id
                  name: discord-secrets
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  key: botguy-secret
                  name: discord-secrets
            - name: TENOR_KEY
              valueFrom:
                secretKeyRef:
                  key: botguy-tenor-key
                  name: discord-secrets
            - name: USER_ID
              valueFrom:
                secretKeyRef:
                  key: abspen1-id
                  name: discord-secrets
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  key: REDIS_PASS
                  name: redis
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  key: REDIS_HOST
                  name: redis
            - name: FINNHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  key: finnhub-token
                  name: discord-secrets
